//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Hand Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @HandControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @HandControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Hand Controls"",
    ""maps"": [
        {
            ""name"": ""MouseControls"",
            ""id"": ""1890efee-d57b-493b-80b8-85b9fdc09ef6"",
            ""actions"": [
                {
                    ""name"": ""MouseHold"",
                    ""type"": ""Button"",
                    ""id"": ""9e67e6d2-c1b9-46f3-ac75-5acaaea8be50"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bcc269e1-82a9-4acb-98ab-5c0922dc1a8a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MouseControls
        m_MouseControls = asset.FindActionMap("MouseControls", throwIfNotFound: true);
        m_MouseControls_MouseHold = m_MouseControls.FindAction("MouseHold", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MouseControls
    private readonly InputActionMap m_MouseControls;
    private IMouseControlsActions m_MouseControlsActionsCallbackInterface;
    private readonly InputAction m_MouseControls_MouseHold;
    public struct MouseControlsActions
    {
        private @HandControls m_Wrapper;
        public MouseControlsActions(@HandControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseHold => m_Wrapper.m_MouseControls_MouseHold;
        public InputActionMap Get() { return m_Wrapper.m_MouseControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseControlsActions set) { return set.Get(); }
        public void SetCallbacks(IMouseControlsActions instance)
        {
            if (m_Wrapper.m_MouseControlsActionsCallbackInterface != null)
            {
                @MouseHold.started -= m_Wrapper.m_MouseControlsActionsCallbackInterface.OnMouseHold;
                @MouseHold.performed -= m_Wrapper.m_MouseControlsActionsCallbackInterface.OnMouseHold;
                @MouseHold.canceled -= m_Wrapper.m_MouseControlsActionsCallbackInterface.OnMouseHold;
            }
            m_Wrapper.m_MouseControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MouseHold.started += instance.OnMouseHold;
                @MouseHold.performed += instance.OnMouseHold;
                @MouseHold.canceled += instance.OnMouseHold;
            }
        }
    }
    public MouseControlsActions @MouseControls => new MouseControlsActions(this);
    public interface IMouseControlsActions
    {
        void OnMouseHold(InputAction.CallbackContext context);
    }
}
